Publish dependency changes to event queue
windbreaker-io/npm-watcher pull request #5
Opened 2017-09-06 02:26 UTC by charlieduong94

2017-09-06 13:47 UTC, austinkelleher requested changes

2017-09-06 13:47 UTC, austinkelleher commented on src/UpdatesPublisher.js
> +      const update = DependencyUpdate.wrap({
I think we should still wrap and check for errors here. We shouldn't bother publishing if errors occurred and should definitely log them.

2017-09-06 13:48 UTC, austinkelleher commented
Also we should merge your other PR merged first so that the CI can pass here.

2017-09-09 22:02 UTC, charlieduong94 commented on package.json
> +    "require": [ "require-self-ref" ]
No need to add `require('require-self-ref')` to the top of every test file with this.

2017-09-10 18:04 UTC, charlieduong94 commented
@Druotic @austinkelleher pls review.

2017-09-11 02:46 UTC, Druotic approved these changes

2017-09-17 19:52 UTC, merged